### ISSUE TITLE
VideoOperate我要具体如何使用API点赞呢

### ISSUE THREAD

**Issue by wushengzhong** [Passkou/bilibili_api#1]
能不能麻烦给个例子？

**Comment by Passkou** [comment]
from bilibili_api.video import VideoOperate
    from bilibili_api import Verify

    # 验证类
    verify = Verify(sessdata="SESSDATA", csrf="bili_jct")

    # 类初始化
    videoOp = VideoOperate(aid=96426930, verify=verify)

    # 点赞，默认为True，False为取消点赞
    videoOp.like(True)

**Comment by wushengzhong** [comment]
好的 非常感谢！
