### ISSUE TITLE
使用收藏功能报错bilibili_api.src.exception.BiliException: 返回code不为0。错误代码：-400, 信息：请求错误

### ISSUE THREAD

**Issue by qianghuohhh** [Passkou/bilibili_api#10]
from bilibili_api.user import UserInfo
from bilibili_api import Verify
from bilibili_api.video import VideoOperate
from bilibili_api.video import VideoInfo
video_info = VideoInfo(bvid=BV号,verify=Verify(sessdata=, csrf=))
a=video_info.get_media_list()
print（a）
video_info = VideoOperate(bvid=BV号,verify=Verify(sessdata=, csrf=))
print(video_info)
video_info.like(1)
video_info.favorite(media_list=["id号"],mode=1)

其中like功能可以正常使用，而favorite功能报错
Traceback (most recent call last):
  File "D:/python/Python37-32/bili007.py", line 11, in <module>
    video_info.favorite(media_list=[""],mode=1)
  File "D:\python\Python37-32\lib\site-packages\bilibili_api\src\video.py", line 407, in favorite
    post()
  File "D:\python\Python37-32\lib\site-packages\bilibili_api\src\utils.py", line 176, in __call__
    raise exception.BiliException(con["code"], con["message"])
bilibili_api.src.exception.BiliException: 返回code不为0。错误代码：-400, 信息：请求错误

不知道是哪里出问题了，大佬可以帮忙看下吗

**Comment by Passkou** [comment]
已修复，更新至1.3.3版本即可
b站这个api还在使用aid来进行收藏。。所以提供bvid就出错了

**Comment by qianghuohhh** [comment]
> 已修复，更新至1.3.3版本即可
> b站这个api还在使用aid来进行收藏。。所以提供bvid就出错了

好的，感谢大佬
