### ISSUE TITLE
又是我，这个不知道是不是bug

### ISSUE THREAD

**Issue by wangcunyuan666** [Passkou/bilibili_api#100]
![图片](https://user-images.githubusercontent.com/74954772/103452099-ab0f9600-4d06-11eb-8062-b52676378729.png)
在编写如图程序的时候，不断地在图中高亮的位置报错412，无法解决.

**Comment by Passkou** [comment]
因为项目特殊性吗，412状态码不是BUG，而是b站风控策略，无法解决，要设置代理
