### ISSUE TITLE
给视频发送弹幕的函数中有关键字错误

### ISSUE THREAD

**Issue by The-BlueFish** [Passkou/bilibili_api#106]
类型：漏洞
版本：3.1.6
video.py 中的第638行，send_danmuku()函数API字典的关键字访问有误，导致运行失败
源码 `api = API["video"]["operate"]["send_danmaku"]`
在改成 `api = API["video"]["danmaku"]["send_danmaku"]` 可以运行了

**Comment by Passkou** [comment]
可能是手贱打错了，毕竟没有智能提示就直接爆炸（）

**Comment by Passkou** [comment]
3.1.7 已解决
