### ISSUE TITLE
在账号已注销的情况下使用 user.get_user_info会出现：“错误代码：-404, 信息：啥都木有”

### ISSUE THREAD

**Issue by xtzhjj** [Passkou/bilibili_api#107]
如题
比如说user.get_user_info(uid=439628323)
bilibili_api.exceptions.BilibiliException: 错误代码：-404, 信息：啥都木有

**Comment by Passkou** [comment]
这边建议你黑入b站数据库去获取被注销账号的信息

**Comment by xtzhjj** [comment]
哈哈哈哈作者太可爱了哈哈哈哈
