### ISSUE TITLE
get_danmaku()函数的返回弹幕问题及文档的优化

### ISSUE THREAD

**Issue by Z-Richard** [Passkou/bilibili_api#108]
类型：建议
版本：3.1.7

`get_danmaku()`函数返回的弹幕应该上限设在了2000条左右，并以月份进行区分。如果弹幕条数小于2000条的话，这个函数是可以返回所有弹幕的；如果大于2000条，则按照月份为界限来划分弹幕区别为“当前弹幕”和“历史弹幕”（需要调用`get_history_danmaku_index()`来获取有弹幕的日期）。我不知道这是不是一个很浅显的东西，但对于我这个中度b站用户来说还是需要摸索才能得出这个结论。而且，目前的文档中将`date`的默认值标注成了今天的日期，而实际上返回的逻辑并不是仅仅返回今天的弹幕（而是返回“当前弹幕”），所以这个解释有一些misleading。因此，希望文档能清晰一点（如果有需要的话，我也可以来改写文档）。

**Comment by Passkou** [comment]
你觉得不对可以发PR改一下，我自己本身是不会去研究这些玩意的
