### ISSUE TITLE
文档中一个网页链接死掉了

### ISSUE THREAD

**Issue by wangzihan11** [Passkou/bilibili_api#109]
您的项目给我在工程中很大的帮助
但是bilibili_api/docs/模块/video.md
中评论相关的副标题先的网页链接无法打开了。
想要得到您关于如何使用您的扩展包获得评论的说明

**Comment by wangzihan11** [comment]
已经在通用模块找到了，但是那个链接在点击的时候真的会挂掉

**Comment by Passkou** [comment]
应该是关闭了官网链接更新的时候漏了一些



---原始邮件---
发件人: "Zihan Wang"<notifications@github.com&gt;
发送时间: 2021年1月20日(周三) 晚上8:48
收件人: "Passkou/bilibili_api"<bilibili_api@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [Passkou/bilibili_api] 文档中一个网页链接死掉了 (#109)




 
已经在通用模块找到了，但是那个链接在点击的时候真的会挂掉
