### ISSUE TITLE
更新api

### ISSUE THREAD

**Issue by wwwanjian** [Passkou/bilibili_api#11]
b站使用新的BV号，有时间更新一下BV号api嘛？

**Comment by Passkou** [comment]
参见：[bilibili_api.src.utils](https://github.com/Passkou/bilibili_api/blob/master/bilibili_api/src/utils.py#L195)

**Comment by jingyuexing** [comment]
BV号和AV号都是同时在使用的，所以无伤大雅，后端返回的数据当中就有AV号

**Comment by jingyuexing** [comment]
我自己也写了一个[bilibiliAPI](https://github.com/jingyuexing/bilibiliAPI)
所有的API我都是放在了Data/API.json文件当中，方便当API更改的时候修改，以配置文件式的方式

**Comment by wwwanjian** [comment]
好的，star一下
