### ISSUE TITLE
好像没找到发布专栏的api

### ISSUE THREAD

**Issue by wkfyynh** [Passkou/bilibili_api#110]
在article模块中没有发现发布专栏文章相关的api，后续能增加下吗？

**Comment by Passkou** [comment]
b站用了比较特殊的格式，发专栏不难，格式转换才难，之后有考虑研究一下markdown转b站专栏格式的代码，看看吧



---原始邮件---
发件人: "wkfyynh"<notifications@github.com&gt;
发送时间: 2021年1月23日(周六) 晚上6:04
收件人: "Passkou/bilibili_api"<bilibili_api@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Passkou/bilibili_api] 好像没找到发布专栏的api (#110)




 
在article模块中没有发现发布专栏文章相关的api，后续能增加下吗？

**Comment by wkfyynh** [comment]
好的

**Comment by wkfyynh** [comment]
请问下你是怎么找到相关api的源请求路径的呢？是通过爬虫的吗，小白一个。想找下专栏发布的rest接口。

**Comment by Passkou** [comment]
浏览器的F12（建议Chrome或Firefox）或者Fiddler来记录请求信息然后分析都可以

**Comment by wkfyynh** [comment]
谢谢！
