### ISSUE TITLE
send_msg方法报错

### ISSUE THREAD

**Issue by Mizar6** [Passkou/bilibili_api#113]
传入Verify后，调用get_self_info方法正常。
但使用send_msg时会报：bilibili_api.exceptions.BilibiliException: 错误代码：-111, 信息：csrf 校验失败

**Comment by Passkou** [comment]
Verify有传入csrf参数吗？涉及到 POST、DELETE请求必须提供CSRF（存在修改数据）

**Comment by Mizar6** [comment]
> Verify有传入csrf参数吗？涉及到 POST、DELETE请求必须提供CSRF（存在修改数据）

有的，用的是在浏览器中查看的cookie信息中的“bili_jct”。
而且刚才试了一下，
video.set_like(bvid="BV1hZ4y1g7DJ", status=True, verify=verify)
这样去给你的视频点赞也是没问题的。
但是send_msg还是会报错。
我还有其他方法可以测试一下嘛？
另外不太明白你最后说的“存在修改数据”是什么意思。

**Comment by Passkou** [comment]
我测试一下，其他没问题就应该是我这边的问题了，存在修改数据就是比如你发送的信息，会修改对方服务器上的数据，就需要CSRF校验，感兴趣的话具体的你可以百度查查原理

**Comment by Mizar6** [comment]
> 我测试一下，其他没问题就应该是我这边的问题了，存在修改数据就是比如你发送的信息，会修改对方服务器上的数据，就需要CSRF校验，感兴趣的话具体的你可以百度查查原理

好的，谢谢。 大概明白，那点赞应该也是修改了对方服务器的数据的。

**Comment by Passkou** [comment]
刚刚测试了一下，可能是b站改了接口，现在正在修复了

**Comment by Passkou** [comment]
`pip install bilibili_api==3.1.8`

3.1.8版本已修复

**Comment by Mizar6** [comment]
好的，刚才我也试了下，没问题。 再次感谢~
