### ISSUE TITLE
获取历史弹幕失败

### ISSUE THREAD

**Issue by und3r5h4ft** [Passkou/bilibili_api#116]
类型：漏洞
版本：3.2.0
用了以下这段代码来获取历史弹幕：
danmaku = video.get_danmaku(bvid=‘BV1bz4y1r7Ug’, verify=verify, date=datetime.strptime('2021-2-1', '%Y-%m-%d'))，
只能获取到空值，请问是什么原因？

**Comment by Passkou** [comment]
我研究一下

**Comment by Passkou** [comment]
找到原因了，API搞错了，没有及时把获取历史弹幕的API更新

**Comment by Passkou** [comment]
尝试v3.2.1
`pip install bilibili-api==3.2.1`

**Comment by Wang-Haining** [comment]
> 尝试v3.2.1
> `pip install bilibili-api==3.2.1`

我试了一下
`
filed=video.get_danmaku(bvid='BV1bz4y1r7Ug', verify=verify,
                    date=datetime.strptime('2021-2-1', '%Y-%m-%d'))
current=video.get_danmaku(bvid='BV1bz4y1r7Ug', verify=verify,
                    date=None)
filed[0].send_time == current[0.send_time
`
filed和current的数据是一样的，应该都是当前弹幕。

**Comment by Passkou** [comment]
> 
> 
> > 尝试v3.2.1
> > `pip install bilibili-api==3.2.1`
> 
> 我试了一下
> 
> ```python
> filed=video.get_danmaku(bvid='BV1bz4y1r7Ug', verify=verify,
>                     date=datetime.strptime('2021-2-1', '%Y-%m-%d'))
> 
> current=video.get_danmaku(bvid='BV1bz4y1r7Ug', verify=verify,
>                     date=None)
> 
> filed[0].send_time == current[0.send_time
> ```
> 
> filed和current的数据是一样的，应该都是当前弹幕。

他这个日期本来就不对，我这只是按照b站api格式写的

**Comment by und3r5h4ft** [comment]
> > > 尝试v3.2.1
> > > `pip install bilibili-api==3.2.1`
> > 
> > 
> > 我试了一下
> > ```python
> > filed=video.get_danmaku(bvid='BV1bz4y1r7Ug', verify=verify,
> >                     date=datetime.strptime('2021-2-1', '%Y-%m-%d'))
> > 
> > current=video.get_danmaku(bvid='BV1bz4y1r7Ug', verify=verify,
> >                     date=None)
> > 
> > filed[0].send_time == current[0.send_time
> > ```
> > 
> > 
> > filed和current的数据是一样的，应该都是当前弹幕。
> 
> 他这个日期本来就不对，我这只是按照b站api格式写的

请问日期哪里不对？另外我发现，获取到的弹幕只能是前六分钟的，如果视频长度超过6分钟，后面的弹幕就会获取不到。

**Comment by Wang-Haining** [comment]
辛苦，过年好
