### ISSUE TITLE
connect_all_LiveDanmaku 无法正常使用

### ISSUE THREAD

**Issue by JoinChang** [Passkou/bilibili_api#117]
使用 `connect_all_LiveDanmaku(*room_list)` 报错：

```
RuntimeError: asyncio.run() cannot be called from a running event loop
```

已知将 live.py 此处的 `asyncio.run()` 修改为 `asyncio.create_task()` 可解决

![image](https://user-images.githubusercontent.com/35451392/107492185-192d5f80-6bc7-11eb-9f1a-6d02e1f261fb.png)

对 Python 不熟悉，请问有其他方式解决这问题吗？

**Comment by Passkou** [comment]
报错不是说了吗，你loop已经在运行了，我这个设计本意是不会异步的用户可以简单调用，你既然已经用异步了就应该要自行控制

**Comment by JoinChang** [comment]
> 报错不是说了吗，你loop已经在运行了，我这个设计本意是不会异步的用户可以简单调用，你既然已经用异步了就应该要自行控制

单独 room.connect() 解决了

**Comment by Passkou** [comment]
不过还是有改进空间
