### ISSUE TITLE
上传视频 API 在视频文件本身过大的时候会 timeout

### ISSUE THREAD

**Issue by valkjsaaa** [Passkou/bilibili_api#118]
我发现上传视频 API 在视频文件本身过大的时候会 timeout，我尝试手动给 aiohttp 设置更大的 timeout 可能可以解决：https://github.com/valkjsaaa/bilibili_api/commit/2fe5f7142d4505a527c4a0d8b61a962da530e6bd

不过设置 timeout 感觉不是长久之计，有什么办法能够让 sess.put 返回某种 progress ，并且只要有 progress 就不 timeout 吗？

**Comment by Passkou** [comment]
![图片](https://user-images.githubusercontent.com/45550579/108008576-a2b3b600-703b-11eb-80f3-f0c3e039675c.png)
设置成0或者None貌似可以永不超时：<https://docs.aiohttp.org/en/stable/client_quickstart.html#timeouts>

**Comment by valkjsaaa** [comment]
有道理，但是这么操作我又担心如果网络出现问题会永久卡死在这里，不过可能可以是一个暂时的解决方案
