### ISSUE TITLE
对 issues 的建议

### ISSUE THREAD

**Issue by xiangxiangxiong9** [Passkou/bilibili_api#123]
模板是个好东西，也许可以拿来规范一下.... [官方文档](https://docs.github.com/cn/github/building-a-strong-community/configuring-issue-templates-for-your-repository)
就是这玩意似乎得在默认分支下，可以自动添加标签0.0
[ 看到后可以立即close这个issue :) ]

**Comment by Passkou** [comment]
然而你自己也没按模板发（）
这东西只是个建议，并不是强制，还是有很多人不遵守的
