### ISSUE TITLE
问题; 无法获取用户收藏夹内容。

### ISSUE THREAD

**Issue by Quandong-Zhang** [Passkou/bilibili_api#126]
运行之后没有报错，但也没有输出。
可以看到这位用户的收藏夹是公开的。求解答。
以下是code
from bilibili_api import user
a=user.get_favorite_list_content_g(182742648)
for e in a:
    print(e)
（print（e）那个打缩进了，但github好像显示不出来）
运行后是这样
>>> 
可以看到没有输出
直接看a的内容
>>> a
<generator object get_favorite_list_content_g at 0x000000DB1FE71DD0>
不知道是什么意思，求解答。

**Comment by Passkou** [comment]
这是生成器语法。
```python
for fav in fav_g:
    # 这里处理 fav
   print(fav)
```

**Comment by Quandong-Zhang** [comment]
> 这是生成器语法。
> 
> ```python
> for fav in fav_g:
>     # 这里处理 fav
>    print(fav)
> ```

是打两个缩进吗

**Comment by Passkou** [comment]
不是缩进，我是说这个方法会返回一个生成器，你知不知道python的生成器语法？你需要使用for来迭代。
具体可以参考一下这个：https://www.runoob.com/python3/python3-iterator-generator.html

**Comment by Passkou** [comment]
方法后缀是 _g 的都会返回一个生成器，这样做是方便一边请求数据一边处理数据

**Comment by Quandong-Zhang** [comment]
已解决，谢谢大神。
