### ISSUE TITLE
想了解一下是否转发动态只能得到 560 个 (左右)

### ISSUE THREAD

**Issue by ajz34** [Passkou/bilibili_api#13]
因为确实是看到 https://github.com/Passkou/bilibili_api/blob/690d98d6b041910eab71c8e9900f7a261288b03d/bilibili_api/src/dynamic.py#L281 那边的 560 是 Hardcode 进去的
我在一个 2000 转发的动态里，如果把 560 去掉，能得到 618 条信息，但还是没办法得到所有的转发
即使是在网页里滚到”没有更多啦(〜￣△￣)〜“也拿不到 T.T
也在一些讨论自制 JS 脚本抽奖的文章里看到非官方途径是不可能拿到所有转发信息
我就好奇是否 Bilibili 确实不允许获取所有转发情况……不能的话会不会很对不起没有走非官方抽奖途径的用户 0.0

**Comment by Passkou** [comment]
就是有限制啊。。可能我之前没测准，但是得不到全部的信息的

**Comment by ajz34** [comment]
感谢这么快的回复 :heart_eyes:
好吧，真的复杂 T.T
我先 close 了吧，真的只是想了解一下 (〜￣△￣)〜
