### ISSUE TITLE
b站是不是不让通过api操作三连或者弹幕了？我试着都是csrf 校验失败

### ISSUE THREAD

**Issue by duyuucl** [Passkou/bilibili_api#15]
exception返回的message就是bilibili_api.src.exception.BiliException: 返回code不为0。错误代码：-111, 信息：csrf 校验失败

可以获取视频的信息，但是不能三连或者弹幕。不知道是我太蠢还是b站不给力😂

**Comment by Passkou** [comment]
你实例化Verify的时候传入csrf参数吗，对数据的修改都要csrf的，从b站的cookie里头找，bili_jct的值就是csrf

**Comment by duyuucl** [comment]
可以了，我重新登陆可能用的csrf不对。无比尴尬。。。。。谢谢谢谢
