### ISSUE TITLE
3月b站就不支持av号改成bv了请问如何解决这个问题？

### ISSUE THREAD

**Issue by Jiuyuedongyang** [Passkou/bilibili_api#17]

**Comment by Passkou** [comment]
API仍然支持av号，部分API仍然只支持av号（不知道为什么官方还没更新。。），现有API可以传入bvid（wiki忘记更新了）。新API正在开发中，如果有其他需要可以自行修改一下代码适合自己使用。

**Comment by Mart20191012** [comment]
大部分还是可以用av号的，而且网页也直接可以用av号打开
