### ISSUE TITLE
注释建议

### ISSUE THREAD

**Issue by Gary2018X** [Passkou/bilibili_api#21]
类型：建议

版本：2.0.0

banggumi.py的长评（get_long_comments_raw、get_long_comments）注释是短评，需要注意一下，虽然不影响使用
![image](https://user-images.githubusercontent.com/56428019/90325058-4e0a8200-dfa9-11ea-8961-86d55c1408d3.png)

**Comment by Passkou** [comment]
应该是复制粘贴的时候没改
