### ISSUE TITLE
第三方库开发方便设置自动安装依赖库吗

### ISSUE THREAD

**Issue by Gary2018X** [Passkou/bilibili_api#28]
![image](https://user-images.githubusercontent.com/56428019/90514110-4eff0780-e193-11ea-834c-c6ceea87b09d.png)

**Comment by Passkou** [comment]
设置了，但是好像并未生效

**Comment by Passkou** [comment]
原因找到了，setup.py写错了

**Comment by Gary2018X** [comment]
对，我看有报错
