### ISSUE TITLE
读取直播间大航海的时候一直会少三个

### ISSUE THREAD

**Issue by zcgeng** [Passkou/bilibili_api#29]
类型：BUG

版本：2.0.2

读取直播间大航海的时候一直会少三个。
```
from bilibili_api import live
c = live.get_dahanghai(21721813)
len(c)
# 164
# 然而事实上有167个
```
![image](https://user-images.githubusercontent.com/13724617/91485078-3ae49580-e878-11ea-9064-09eeda5c7fd7.png)

**Comment by zcgeng** [comment]
在这里加上这一段就能fix
https://github.com/Passkou/bilibili_api/blob/4095b8d53f2c0eb295309cd675cc2ba4a41ab832/bilibili_api/live.py#L177
```
        if page == 1:
            if len(resp["top3"]) == 0:
                break
            count += len(resp["top3"])
            users += resp["top3"]
            if callable(callback):
                callback(resp["top3"])
```

**Comment by Passkou** [comment]
感谢指出，修好了

**Comment by chickenjohn** [comment]
这个问题好像又出现了
我用的版本：6.1.2
`get_dahanghai()`返回的最后一个page少三个
