### ISSUE TITLE
send_dynamic 返回 TypeError，但动态发送成功

### ISSUE THREAD

**Issue by Kotoki1337** [Passkou/bilibili_api#30]
类型：提问/漏洞(?)
API 版本：2.0.3
Python 版本：3.8.5 32-bit

Example code：
```python
from bilibili_api import Verify, dynamic

verify = Verify("", "")
dynamic.send_dynamic(text="Testing", verify=verify)
```

Vscode报错：
``argument of type 'NoneType' is not iterable``
![image](https://user-images.githubusercontent.com/35394151/91653635-19341a00-ead5-11ea-936e-f0ba13aa4a3a.png)
但实际动态已经发送成功。
这是 function 问题还是我的问题..

**Comment by Passkou** [comment]
原因是源代码中因为传入了None，然后未对其设置默认值就直接当做字典来用导致判断出错了。下一版本修正
