### ISSUE TITLE
新增关注分组

### ISSUE THREAD

**Issue by lovelyxmj** [Passkou/bilibili_api#42]
类型：建议

版本：V2

我想要个设置分组的接口可以吗qwq

**Comment by Passkou** [comment]
具体是什么意思呢？是哪个方面的设置分组？

**Comment by lovelyxmj** [comment]
就是那个设置关注的人的分组

**Comment by Passkou** [comment]
好的，回头看看尽快加上

**Comment by Passkou** [comment]
你要的功能我发布了一个beta版本，可以先试试：
`pip install bilibili-api==2.1.1b0`
已经安装好了可以加个`--upgrade`升级一下

**Comment by lovelyxmj** [comment]
啊这，我刚刚发了个PR就加入了这个功能

**Comment by lovelyxmj** [comment]
不过还是麻烦你了，对了，我的PR求合并qwq

**Comment by Passkou** [comment]
我已经把这玩意写进去了还合并干啥啊23333。如果你要写之前就打个招呼，我就不写了

**Comment by zhangli709** [comment]
类型：建议

版本：V2

我想要个上传视频的接口可以吗qwq
