### ISSUE TITLE
pip安装不上

### ISSUE THREAD

**Issue by lovelyxmj** [Passkou/bilibili_api#43]
类型：漏洞
版本：V2
我的pip安装不上这个库qwq
![image](https://user-images.githubusercontent.com/53249654/92918312-e3424e80-f461-11ea-8d83-fc31eb009a68.png)

**Comment by Passkou** [comment]
`pip -V`，看看你的pip版本多少，有可能是pip版本太老了

**Comment by lovelyxmj** [comment]
最新了已经

**Comment by Passkou** [comment]
Python37？试试升级到38，我的开发环境是3.8的，README上面的忘记改了

**Comment by lovelyxmj** [comment]
我装上了，clone的仓库然后自己打的whl文件安装上的
