### ISSUE TITLE
新增上传视频接口

### ISSUE THREAD

**Issue by zhangli709** [Passkou/bilibili_api#45]
### 类型：需求

版本：V2

我想要个上传视频的接口可以吗qwq

**Comment by Passkou** [comment]
这个可能有点麻烦emmmm，而且感觉不太常用，考虑一下

**Comment by eligao** [comment]
+1 for this

**Comment by phigrey** [comment]
+1 自动化

**Comment by Passkou** [comment]
我想办法写一下吧（雾）

**Comment by phigrey** [comment]
需要小助手的话，可以叫上我。

**Comment by Passkou** [comment]
V3.0.0b0版本加上了，目前在测试阶段，可以先行尝试
https://github.com/Passkou/bilibili_api/releases/tag/3.0.0b0
https://pypi.org/project/bilibili-api/3.0.0b0/
pip更新一下应该就能用了

**Comment by phigrey** [comment]
`Cannot connect to host upos-sz-upcdnbda2.bilivideo.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate` 在上传视频的时候， 出现这样的错误。请问，是 SESSDATA, CSRF 的问题吗？

**Comment by Passkou** [comment]
> 
> 
> `Cannot connect to host upos-sz-upcdnbda2.bilivideo.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate` 在上传视频的时候， 出现这样的错误。请问，是 SESSDATA, CSRF 的问题吗？

不知道为什么我弄的时候也会这样，提示的信息是SSL安全错误，和verify无关。多试几次就好了，这个问题还待解决，很迷惑的一个问题

**Comment by phigrey** [comment]
OK. 我这边完整的故事是这样的：因为之前用的是  MacOS + poetry + python 3.7，今天刚升级到3.8.6。https://stackoverflow.com/questions/52805115/certificate-verify-failed-unable-to-get-local-issuer-certificate
处理了下，就可以了。

**Comment by 501938568** [comment]
还是预览版本吧 更新用pip install bilibili-api --upgrade --pre

**Comment by Passkou** [comment]
3.0.0版本已加入该功能
