### ISSUE TITLE
bilibili_api.video.get_comments()会吞掉部分评论

### ISSUE THREAD

**Issue by NavigatorKepler** [Passkou/bilibili_api#46]
我尝试爬取视频的评论，但是发现有一些评论被吞了。

    import bilibili_api
    a = bilibili_api.video.get_comments(bvid='BV13E411p7pu')    # 当时实际评论数为9865
    len(a)    # 7618

如果是一些评论数比较少的，就不会出现这个问题，

**Comment by Passkou** [comment]
按理来说是逐页获取的，如果一两百页的没问题，就说明是b站api的问题
________________________________
