### ISSUE TITLE
字典调用了切片导致的错误

### ISSUE THREAD

**Issue by Stele1024** [Passkou/bilibili_api#5]
`src/user.py` 文件里的 `UserInfo`类 的`get_vedio`方法，最后的 `return video_lists[:limit]` 或者`return first_page["list"][:limit]` 这里。字典调用了切片方法，会报错：
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
TypeError: unhashable type: 'slice'
```
字典不能哈希。直接返回`video_lists["vlist"]`或者返回`first_page["list"]["vlist"]`就可以返回所有的视频的json格式的数据。

还有，你B站的简介的粉丝群QQ搜不到[滑稽]！

**Comment by Passkou** [comment]
已修复，更新一下就可以了

**Comment by Stele1024** [comment]
好滴
