### ISSUE TITLE
获取用户的视频总浏览数和观看总时间

### ISSUE THREAD

**Issue by ZHJ0125** [Passkou/bilibili_api#52]
类型：需求

版本：2.1.2

能不能实现 “获取用户的**视频总浏览数**和**观看总时间**” 呢?

**Comment by Passkou** [comment]
b站都没有这个功能我怎么实现啊2333

**Comment by ZHJ0125** [comment]
B站确实没有这个功能

**Comment by ZHJ0125** [comment]
有什么办法可以实现吗? 我是个小白，请教一下您

**Comment by Passkou** [comment]
b站都没有这个功能没法实现吧？你就看你自己的观看总时间都看不到吧

**Comment by ZHJ0125** [comment]
是的，自己的观看总时间也看不了。

emmm，谢谢您了👍
