### ISSUE TITLE
【提问】怎么样获取一个用户的粉丝数啊，有方法吗？

### ISSUE THREAD

**Issue by Yang161941** [Passkou/bilibili_api#53]
【提问】
版本：bilibili-api        2.1.2
怎么样获取一个用户的粉丝数啊，有方法吗？

**Comment by Passkou** [comment]
<https://passkou.com/docs/bilibili_api/%E6%A8%A1%E5%9D%97/user#get_relation_info>
b站的API太乱了确实有时候摸不着头脑

**Comment by Yang161941** [comment]
谢了，自己找到解决方法了
