### ISSUE TITLE
【提问】user.get_up_info获取到的信息只有{}

### ISSUE THREAD

**Issue by Yang161941** [Passkou/bilibili_api#55]
【提问】
版本：bilibili-api        2.1.2
我在使用以下代码（简化过的）时获得的数据只有一个{}，想问问这是怎么回事（我是萌新）
from bilibili_api import user
uid = 114514
x = user.get_up_info(uid=uid)
print(x)

输出：

{}

**Comment by Passkou** [comment]
原因找到了，正在修复，他这个突然要一些特定的Cookies才给信息了。。

**Comment by Yang161941** [comment]
ok,问题已解决
