### ISSUE TITLE
【反馈】弹幕功能关闭会导致返回空白数据

### ISSUE THREAD

**Issue by oodzfa** [Passkou/bilibili_api#57]
输入：
`from bilibili_api import video`
`v = video.get_danmaku("BV1e7411o7GG")`
`print(v)`

输出：
`[]`

**Comment by Passkou** [comment]
弹幕功能关闭你还怎么获取弹幕数据？

**Comment by oodzfa** [comment]
获取评论的时候遇到功能关闭会报错
