### ISSUE TITLE
能更加方便地获取cookie吗

### ISSUE THREAD

**Issue by 501938568** [Passkou/bilibili_api#60]
我最近用这个api+tkinter写了一个小的三连GUI玩具，但是cookie的获取还是比较麻烦。可不可以直接通过账号密码方式获取到cookie？
另外这个小玩具方便的话，也想请大大指教一下，看看还有无什么进一步的空间，谢谢。

**Comment by Passkou** [comment]
要通过登录获取的话得要验证码，你可以尝试一下浏览器自动化控制selenium，登录后传回cookies就行了。tkinter我没用过所以不是很了解。

**Comment by 501938568** [comment]
可以了 设置了第一次登录的时候打开网页登录 登录后保存cookie到本地，之后用cookie登录
