### ISSUE TITLE
想问下video.py里面6到11行的字体是用什么API生成的

### ISSUE THREAD

**Issue by DZ9** [Passkou/bilibili_api#61]
想问下video.py里面6到11行的字体是用什么API生成的
![image](https://user-images.githubusercontent.com/6756880/95942126-f6578e00-0e14-11eb-880e-1b18f9293565.png)

**Comment by 501938568** [comment]
百度下ASCII art应该有吧

**Comment by Passkou** [comment]
https://www.jianshu.com/p/fca56d635091

**Comment by DZ9** [comment]
> https://www.jianshu.com/p/fca56d635091

thx
