### ISSUE TITLE
小白求问

### ISSUE THREAD

**Issue by tuyurong** [Passkou/bilibili_api#62]
P大，想用您的API爬数据，第一步就报错了，看了很久也不知道是哪里出了问题。我是初学者，基本的Python语法都不熟，如果有些低级错误请见谅。
from bilibili_api import Verify
from bilibili_api.video import VideoInfo
from bilibili_api.video import Danmaku
verify = Verify(sessdata="6b49d6ef..........", csrf="a2e7f2dc44............")
video_info = VideoInfo(bvid="BV1gC4y1h722", verify=verify)
 
danmu = video_info.get_danmaku()
for i in danmu:
    print(i.text)

报错是这样的：
  File "<ipython-input-26-49cc738003fb>", line 1
    from bilibili_api import Verify
                                  ^
SyntaxError: invalid character in identifier

**Comment by Passkou** [comment]
你这个语法还是v1的语法啊...现在都是v2版本了（笑哭）
先更新一下吧 `pip install --upgrade bilibili_api`，然后检查一下python版本是不是3.8，再看看 https://github.com/Passkou/bilibili_api#%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B

**Comment by makelove** [comment]
> 你这个语法还是v1的语法啊...现在都是v2版本了（笑哭）
> 先更新一下吧 `pip install --upgrade bilibili_api`，然后检查一下python版本是不是3.8，再看看 https://github.com/Passkou/bilibili_api#%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B

Python 3.7
`pip install bilibili_api` 只获得bilibili-api-2.1.4
能不能提醒一下要升级Python 3.8 ？
另外我使用python setup.py install源码，Python 3.7也能顺利安装
为什么要强调Python 3.8？
