### ISSUE TITLE
3.0测试版中user模块获得up投稿信息改为迭代器方法后怎么获取信息

### ISSUE THREAD

**Issue by 501938568** [Passkou/bilibili_api#64]
get_videos_g()方法中用迭代器生成对象。怎么获取投稿视频详细信息，如封面ur和描述l等。
希望能写个文档或者定义一下用法。

**Comment by Passkou** [comment]
https://github.com/Passkou/bilibili_api/blob/develop/docs/%E9%80%9A%E7%94%A8%E8%A7%A3%E9%87%8A.md#%E5%BE%AA%E7%8E%AF%E8%8E%B7%E5%8F%96%E6%95%B0%E6%8D%AE%E5%8F%82%E6%95%B0%E8%AF%B4%E6%98%8E
这儿有，原理是一样的，其实你也可以百度查一下python生成器，实际上就是使用了yield语法

**Comment by 501938568** [comment]
好的，改好了。刚刚没获取到信息是我自己一个语法写错了。
