### ISSUE TITLE
【建议】进一步放宽对返回数据解析的限制

### ISSUE THREAD

**Issue by Gary2018X** [Passkou/bilibili_api#67]
如果返回的数据没有code关键词就会报错

**Comment by Gary2018X** [comment]
比如这个接口https://bvc.bilivideo.com/pbp/data?r=loader&cid=223345500&aid=286722077&bvid=BV16f4y197qE

**Comment by Passkou** [comment]
但是这种接口并不常用，而且我也没遇到过

**Comment by Gary2018X** [comment]
这
