### ISSUE TITLE
找不到get_short_comments

### ISSUE THREAD

**Issue by c20192138** [Passkou/bilibili_api#72]
```python3
from bilibili_api import video, Verify,bangumi
......
comments=bangumi.get_short_comments(season_id=bangumi.get_meta(media_id=md)['media']['season_id'])
#AttributeError: module 'bilibili_api.bangumi' has no attribute 'get_short_comments'
```

**Comment by Passkou** [comment]
新版改用了生成器语法：https://github.com/Passkou/bilibili_api/blob/master/bilibili_api/bangumi.py#L72
用法参照：[文档](https://passkou.com/bilibili_api/docs/%E9%80%9A%E7%94%A8%E8%A7%A3%E9%87%8A#%E5%BE%AA%E7%8E%AF%E8%8E%B7%E5%8F%96%E6%95%B0%E6%8D%AE%E5%8F%82%E6%95%B0%E8%AF%B4%E6%98%8E)
