### ISSUE TITLE
type:提问   版本：3.1    问题：模块bilibili_api.vedio中没有'get_comments'

### ISSUE THREAD

**Issue by tuyurong** [Passkou/bilibili_api#75]

**Comment by tuyurong** [comment]
码：d = video.get_comments (bvid="BV1uv411q7Mv")
print (d)
AttributeError: module 'bilibili_api.video' has no attribute 'get_comments'

**Comment by Passkou** [comment]
https://passkou.com/bilibili_api/docs/%E9%80%9A%E7%94%A8%E8%A7%A3%E9%87%8A#%E5%BE%AA%E7%8E%AF%E8%8E%B7%E5%8F%96%E6%95%B0%E6%8D%AE%E5%8F%82%E6%95%B0%E8%AF%B4%E6%98%8E

**Comment by tuyurong** [comment]
反馈：用get_comments_g接口爬取评论的子评论最多只能爬取三条

**Comment by Passkou** [comment]
V3.1.2已增加获取子评论接口。
文档还没更新，可以使用 video.get_sub_comments_g 来获取。
