### ISSUE TITLE
如何获取动态列表？

### ISSUE THREAD

**Issue by jiangdashao** [Passkou/bilibili_api#77]
我翻了下API，没法获取动态列表啊，就是自己关注的人的最近动态列表

**Comment by Passkou** [comment]
https://passkou.com/bilibili_api/docs/%E6%A8%A1%E5%9D%97/user#get_dynamic

**Comment by jiangdashao** [comment]
我测试了下这个API，返回的是给定UID的用户自己的动态
我指的是"t.bilibili.com"看到的那样的，自己关注的所有人的最近动态

**Comment by Passkou** [comment]
这个暂时还没有实现
