### ISSUE TITLE
问题（不知道是不是bug）

### ISSUE THREAD

**Issue by qq1327466228** [Passkou/bilibili_api#88]
在上传视频的接口的问题
视频上传后 返回也成功了  
然后上传图片 再提交也成功了  在创造中心也有投稿审核中了 但是这个视频加载不出来  我问客服说转码失败了  
在网页的返回结果看这个视频的状态为-30  正常的视频状态是1  导致这个视频没发预览封面选择  审核也看不到视频
请问这个如何解决

**Comment by qq1327466228** [comment]
我用源码跑了一下 吧日志打印看后  发现
在视频上传最后一步提交parts的时候   返回的xml显示
“Invalid encoding type. Only UTF-8 encoding is supported at this time.”
我在headers里面加了"Content-Type", "application/json; charset=UTF-8"  也吧请求的文本UTF-8转码了一下  还是提示这个  我应该怎么修改

**Comment by Passkou** [comment]
完整代码贴一下，回头我看看

**Comment by Passkou** [comment]
长时间未得到反馈，先关了
