### ISSUE TITLE
bangumi - 番剧模块会有什么功能

### ISSUE THREAD

**Issue by jackjieYYY** [Passkou/bilibili_api#9]
海外党想翻墙回去看

打算国内部署台vps翻墙回去

**Comment by Passkou** [comment]
番剧模块就是获取番剧的一些信息，其实番剧就是特殊的视频
与其翻墙回来看不如到资源网站去下，用百度云多香233

**Comment by jackjieYYY** [comment]
> 番剧模块就是获取番剧的一些信息，其实番剧就是特殊的视频
> 与其翻墙回来看不如到资源网站去下，用百度云多香233

百度云狗屎限速 我再充钱我是狗

会有播放链接？我打算做个替换就实现翻墙回去了

**Comment by Passkou** [comment]
这个我之后有空的时候帮你看看再给你答复吧

**Comment by jackjieYYY** [comment]
谢谢大佬，萌新先跪下了。。。

**Comment by Passkou** [comment]
久等了
![img](https://s1.ax1x.com/2020/03/29/GVdVHS.png)
如图所示，番剧每一集旁边会有BV号，我试了当做普通的视频来对待，可以获取下载链接，但是要记得部分番剧要大会员，需要登录

**Comment by jackjieYYY** [comment]
> 久等了
> ![img](https://camo.githubusercontent.com/51e7c3e512ed7f802d9b961a8ac8f8e235f8781e/68747470733a2f2f73312e617831782e636f6d2f323032302f30332f32392f4756645648532e706e67)
> 如图所示，番剧每一集旁边会有BV号，我试了当做普通的视频来对待，可以获取下载链接，但是要记得部分番剧要大会员，需要登录

谢谢大佬~~~

不愧是大佬~~~
