### ISSUE TITLE
video.get_video_info返回信息的格式问题

### ISSUE THREAD

**Issue by wladder** [Passkou/bilibili_api#90]
类型：提问
版本：3.1.1

API返回的信息是**单引号**和”**F**alse“，这不被一些工具认可：
`{'bvid': 'BV1uv411q7Mv', 'aid': 243922477, 'videos': 1, 'tid': 17, 'tname': '单机游戏', 'copyright': 1, 'pic': 'http://i2.hdslb.com/bfs/archive/82e52df9d0221836c260c82f2890e3761a46716b.jpg', 'title': '爆肝９８小时！在MC中还原糖调小镇', `
`'no_cache': False`

而官方API [https://api.bilibili.com/x/web-interface/view?bvid=BV1uv411q7Mv](url) 中返回的是**双引号**和”**f**alse“：
`"code":0,"message":"0","ttl":1,"data":{"bvid":"BV1uv411q7Mv","aid":243922477,"videos":1,"tid":17,"tname":"单机游戏",`
`"no_cache": false`

不清楚这是个别现象还是BUG。

**Comment by Passkou** [comment]
那是因为我转换成Python对象了，你可以直接用。
如果你要导出json格式的信息，应该使用 `json.dumps(python_object)`
