### ISSUE TITLE
发现bug

### ISSUE THREAD

**Issue by wangcunyuan666** [Passkou/bilibili_api#94]
![}}N`73D@~V~4){ SKBMTM 6](https://user-images.githubusercontent.com/74954772/103435482-0039a200-4c4a-11eb-948b-cd8a43883b6f.png)
<img width="385" alt="07b40525dae7db4b439a5d45752e06b" src="https://user-images.githubusercontent.com/74954772/103435484-029bfc00-4c4a-11eb-8bfd-4e9df150ef0a.png">
代码和报错如上图
我如果直接print（dy）是能够正常显示结果的，但是我如果想要像上图一样检索字典的值的时候就会在我迭代器的位置报错
周末要交作业，挺急的

**Comment by Passkou** [comment]
刚刚测试了一下，报错的时候是因为已经没动态了，我可能是忘记检测了，你暂时跳过，之后我修复一下

**Comment by wangcunyuan666** [comment]
大哥，现在有啥我自己能干的事让他正常跑起来么，我周末就交作业了(&gt;﹏<)



---原始邮件---
发件人: "Passkou"<notifications@github.com&gt;
发送时间: 2021年1月1日(周五) 下午4:06
收件人: "Passkou/bilibili_api"<bilibili_api@noreply.github.com&gt;;
抄送: "wangcunyuan666"<1599245782@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [Passkou/bilibili_api] 发现bug (#94)




 
刚刚测试了一下，报错的时候是因为已经没动态了，我可能是忘记检测了，你暂时跳过，之后我修复一下

**Comment by Passkou** [comment]
就按你现在这个写法就行，忽略这个错误

**Comment by wangcunyuan666** [comment]
啥意思呢，我except KeyError 也没用的
关键是有这个错误程序就报错退出了啊





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Passkou/bilibili_api"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月1日(星期五) 下午4:08
收件人:&nbsp;"Passkou/bilibili_api"<bilibili_api@noreply.github.com&gt;;
抄送:&nbsp;"道本"<1599245782@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Passkou/bilibili_api] 发现bug (#94)





 
就按你现在这个写法就行，忽略这个错误

**Comment by Passkou** [comment]
把for循环给包裹起来

**Comment by Passkou** [comment]
我快速修复一下吧，这个问题挺简单的

**Comment by wangcunyuan666** [comment]
多谢大佬！好起来了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Passkou/bilibili_api"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月1日(星期五) 下午4:14
收件人:&nbsp;"Passkou/bilibili_api"<bilibili_api@noreply.github.com&gt;;
抄送:&nbsp;"道本"<1599245782@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Passkou/bilibili_api] 发现bug (#94)





 
我快速修复一下吧，这个问题挺简单的

**Comment by Passkou** [comment]
3.1.6已修复这个问题，这个问题挺简单修复的
