### ISSUE TITLE
有一个bug

### ISSUE THREAD

**Issue by xtzhjj** [Passkou/bilibili_api#95]
a=video.get_danmaku(bvid=某一个BV号)
如果遇到这个视频关闭弹幕功能
不会退出/报错/跳过
会一直卡在那里emmm

**Comment by xtzhjj** [comment]
比如说BV1SD4y1o7hs

**Comment by Passkou** [comment]
下一版本解决

**Comment by Passkou** [comment]
试试测试版：https://github.com/Passkou/bilibili_api/releases/tag/3.1.7b0

**Comment by Passkou** [comment]
3.1.7 已解决
